### ISSUE TITLE
Wrong a priori transparence of dielectric material

### ISSUE THREAD

**Issue by keryell** [triSYCL/ray_tracer#5]
It looks like because of https://github.com/triSYCL/ray_tracer/blob/main/RT_SYCL/material.hpp#L68 the sky is very dark.
With `{ 1, 1, 1 }` it looks good.
It is not clear why attenuation had no effect on anything but the sky... :-(
Another hidden bug to find?
This attenuation should be a color aspect of the material anyway, not hard-coded like that.

**Comment by kraiby30** [comment]
Yea, there was a bug in the code, and fixing it makes the image a whole lot better! 
The fix changes the following result:
![sky_1](https://user-images.githubusercontent.com/47418492/101530642-08ead100-3947-11eb-9262-add29b6d84eb.jpg)

To this:
![glass_1](https://user-images.githubusercontent.com/47418492/101530669-12743900-3947-11eb-8f71-3155e1f4182a.jpg)

Also, we can add a variable for the dielectric material to store the color of the glass instead of hard coding the value to { 1, 1, 1 }.
![redglass](https://user-images.githubusercontent.com/47418492/101530696-1b650a80-3947-11eb-8403-d029334d52a2.jpg)

I'll make a new PR with the bug fix!
